# -*- coding: utf-8 -*-
"""1st.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FugnA7ps4nIxYoOeLSToNO3R5sBCOGzx
"""

ef findRoman(num):
th = ["","M","MM","MMM"]
cen = ["", "C", "CC", "CCC", "CD", "D","DC", "DCC", "DCCC", "CM "]
ten = ["", "X", "XX", "XXX", "XL", "L","LX", "LXX", "LXXX", "XC"]
unit = ["", "I", "II", "III", "IV", "V","VI", "VII", "VIII", "IX"]
thousand = th[num//1000]
hundreds = cen[(num%1000)//100]
tens = ten[(num%100)//10]
unit_digit = unit[num%10]
result = (thousand+hundreds+tens+unit_digit)
return result
if __name__ == "__main__":
num = int(input("Enter a Integer\n"))
print(findRoman(num))

tr = input("Enter Email...\n")
fname = str[:str.index('.')];
lname = str[str.index('.')+1:str.index('@')];
host = str[str.index('@')+1:]
print("your first name : "+fname)
print("your last name : "+lname)
print("hostname : "+ host)

ef findBMI(h,w):
bmiValue = w/(h**2)
if(bmiValue<18.5):
print("Underweighted")
return
if(bmiValue >= 18.5 and bmiValue<24.9):
print("Normal")
return
if(bmiValue >=24.9 and bmiValue<30):
print("Overweighted")
return
print("obesity")
if __name__ == "__main__":
h =float(input("Enter your height\n"))
w =float(input("Enter your weight \n"))
findBMI(h,w)